### PR TITLE
Adds PHP 8.3 as new supported version

### PR DESCRIPTION
**Pull request by fezfez**

### CODE REVIEW

**Comment by boesing** [comment]
https://github.com/laminas/laminas-cache-storage-adapter-filesystem/pull/74#issuecomment-1801395046

**Comment by fezfez** [comment]
@boesing 

i've done the

```
* remove dependency bumps

* remove psalm baseline change
```

but it lead to some error in psalm

**Comment by boesing** [comment]
> [...] but it lead to some error in psalm

That might be due to the fact that psalm version somehow changed:
https://github.com/laminas/laminas-cache-storage-adapter-blackhole/pull/58/files#diff-f37acfaa6b11f575a9a6f41a75fa73a61d0f8ebc2c9b8cddc215d8aca10e44f5R4556

https://github.com/laminas/laminas-cache-storage-adapter-blackhole/pull/58/files#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R23

I recommend just using `composer update --lock` once adding `8.3` to the `composer.json` and/or just updating explicit packages. Maybe just rollback `composer.json` and `composer.lock` to the version from `2.4.x` branch and then add `~8.3.0` constraint and run `composer update --lock`.
That should actually do the trick.

**Comment by Xerkus** [comment]
Superseded by #59

**Pull request closed without merging**
